FROM node:22.22.0-alpine3.23
WORKDIR /app

# Install packages
COPY react/package*.json ./
RUN npm install

# Le code source sera monté via volume
# On expose le port du dev server
EXPOSE 3000

# La commande sera définie dans docker-compose.yml
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]